'use client'
import type { ReactNode } from 'react'
import { Check, ChevronRight, Coins, Lock, Sparkles, X } from 'lucide-react'
import type { MissionDefinition, MissionStatus } from '@/lib/game-types'
import { getLevel } from '@/lib/game-engine'

export function XPBar({xp,compact=false}:{xp:number;compact?:boolean}){const level=getLevel(xp);const progress=Math.min(100,(level.current/level.needed)*100);return <div aria-label={`${level.current} de ${level.needed} XP para o próximo nível`}><div className="mb-2 flex items-end justify-between"><div><p className="eyebrow">{level.title} · Nível {level.level}</p>{!compact&&<b className="text-sm">{level.total.toLocaleString('pt-BR')} XP</b>}</div><span className="text-[10px] text-white/45">{level.current}/{level.needed} XP</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="progress-fill h-full rounded-full bg-gradient-to-r from-river via-leaf to-gold" style={{width:`${progress}%`}}/></div></div>}

export function CurrencyDisplay({value}:{value:number}){return <div className="flex items-center gap-2" title="Moeda exclusivamente virtual, sem valor monetário"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-gold/15 text-gold"><Coins size={16}/></span><div><b className="display block text-sm text-gold">{value.toLocaleString('pt-BR')} RAVOS</b><span className="block text-[8px] text-white/35">MOEDA VIRTUAL</span></div></div>}

export function ChapterProgress({completed}:{completed:number}){return <div className="glass rounded-2xl p-4"><div className="flex justify-between"><div><p className="eyebrow">Capítulo 1</p><b className="display text-sm">O Mapa Desaparecido</b></div><strong className="text-leaf">{completed}/5</strong></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="progress-fill h-full bg-leaf" style={{width:`${completed*20}%`}}/></div></div>}

export function MissionCard({mission,status,onClick}:{mission:MissionDefinition;status:MissionStatus;onClick:()=>void}){const locked=status==='locked';return <button onClick={onClick} disabled={locked} className={`mission-card glass flex w-full items-center gap-4 rounded-2xl p-4 text-left ${locked?'opacity-45':'hover:border-leaf/40'}`}><span className={`flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl font-black ${status==='completed'?'bg-leaf text-ink':status==='in_progress'?'bg-gold text-ink':'bg-white/5 text-white/60'}`}>{status==='completed'?<Check/>:locked?<Lock size={18}/>:mission.number}</span><span className="min-w-0 flex-1"><span className="text-[8px] font-bold tracking-[.18em] text-leaf">{mission.location}</span><b className="display mt-1 block text-sm leading-tight">{mission.title}</b><span className="mt-1 block text-[9px] text-white/40">{locked?'Conclua a missão anterior':status==='completed'?'Missão concluída':mission.subtitle}</span></span><span className="text-right text-[9px] font-bold text-gold">+{mission.reward.xp}<br/>XP</span></button>}

export function PuzzleContainer({eyebrow,title,children}:{eyebrow:string;title:string;children:ReactNode}){return <section className="mx-5 rounded-[28px] border border-white/10 bg-gradient-to-b from-white/[.07] to-transparent p-5 shadow-2xl"><p className="eyebrow">{eyebrow}</p><h2 className="display mt-2 text-2xl font-black leading-tight">{title}</h2><div className="mt-6">{children}</div></section>}

export function CollectibleCard({title,detail,found,icon}:{title:string;detail:string;found:boolean;icon:ReactNode}){return <div className={`glass rounded-2xl p-4 ${found?'border-gold/35':'opacity-40 grayscale'}`}><div className={`mb-3 flex h-10 w-10 items-center justify-center rounded-xl ${found?'bg-gold/15 text-gold':'bg-white/5'}`}>{found?icon:<Lock size={16}/>}</div><b className="display text-xs">{title}</b><p className="mt-1 text-[9px] text-white/40">{found?detail:'Ainda não descoberto'}</p></div>}

export function RewardToast({show,xp,ravos,label}:{show:boolean;xp:number;ravos:number;label?:string}){if(!show)return null;return <div role="status" className="reward-toast fixed left-1/2 top-5 z-[80] w-[calc(100%-32px)] max-w-sm -translate-x-1/2 rounded-2xl border border-leaf/30 bg-[#0b211af2] p-4 shadow-2xl backdrop-blur"><div className="flex items-center gap-3"><Sparkles className="text-gold"/><div><b className="text-sm">{label??'Recompensa recebida'}</b><p className="text-[11px] text-leaf">+{xp} XP · +{ravos} RAVOS</p></div></div></div>}

export function GameDialog({speaker,children,choices,onChoose}:{speaker:string;children:ReactNode;choices:string[];onChoose:(choice:string)=>void}){return <div className="rounded-2xl border border-gold/20 bg-[#0b211a] p-5"><p className="eyebrow text-gold">{speaker}</p><div className="my-4 text-sm leading-7 text-white/75">{children}</div><div className="space-y-2">{choices.map(choice=><button key={choice} onClick={()=>onChoose(choice)} className="w-full rounded-xl border border-white/10 bg-white/[.04] p-3 text-left text-xs font-bold hover:border-leaf/50">“{choice}”</button>)}</div></div>}

export function MissionComplete({chapter=false,onContinue}:{chapter?:boolean;onContinue:()=>void}){return <div className="chapter-reveal text-center"><span className="mx-auto flex h-24 w-24 items-center justify-center rounded-full border border-gold/50 bg-gold/10 text-gold shadow-[0_0_70px_#d8aa5b44]"><Sparkles size={42}/></span><p className="eyebrow mt-7 text-gold">{chapter?'Capítulo concluído':'Missão concluída'}</p><h1 className="display mt-3 text-3xl font-black">{chapter?'O MAPA DESAPARECIDO':'PISTA RECUPERADA'}</h1><p className="mx-auto mt-4 max-w-xs text-xs leading-6 text-white/55">{chapter?'A chuva revela uma nova rota. Uma área de Belém foi desbloqueada.':'Seu progresso foi salvo. A próxima parte do mapa agora está ao seu alcance.'}</p><button onClick={onContinue} className="btn btn-primary mt-7 w-full">{chapter?'VOLTAR À JORNADA':'PRÓXIMA MISSÃO'} <ChevronRight size={16}/></button></div>}

export function Sheet({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="fixed inset-0 z-[70] flex items-end justify-center bg-black/70 p-3" onClick={onClose}><div role="dialog" aria-modal="true" aria-label={title} onClick={event=>event.stopPropagation()} className="sheet-in max-h-[85dvh] w-full max-w-[480px] overflow-y-auto rounded-[28px] border border-white/10 bg-ink p-5"><div className="mb-5 flex items-center justify-between"><h2 className="display text-xl font-bold">{title}</h2><button onClick={onClose} aria-label="Fechar" className="glass rounded-full p-2"><X size={18}/></button></div>{children}</div></div>}
