'use client'
import { useRef,useState } from 'react'
import { Check,Lightbulb,RotateCcw,Sparkles } from 'lucide-react'
import { missions } from '@/data/belem-content'
import type { MissionId } from '@/lib/game-types'
import { MissionComplete,PuzzleContainer } from './game-ui'
import { useGame } from './game-provider'
import { track } from '@/lib/telemetry'

export function MissionExperience({id,replay=false,onComplete,onExit,onNext}:{id:MissionId;replay?:boolean;onComplete:(metrics:{attempts:number;hintsUsed:number;durationMs:number})=>void;onExit:()=>void;onNext:()=>void}){
 const mission=missions.find(m=>m.id===id)!;const {state,dispatch}=useGame();const started=useRef(Date.now());const [picked,setPicked]=useState<string[]>([]);const [attempts,setAttempts]=useState(0);const [message,setMessage]=useState('');const [done,setDone]=useState(false);const used=state.hintsByMission[id]??0
 const solved=picked.join('|')===mission.answer.join('|');const add=(option:string)=>{const allowed=mission.answer.filter(x=>x===option).length>picked.filter(x=>x===option).length;if(picked.length<mission.answer.length&&allowed)setPicked(v=>[...v,option])}
 const verify=()=>{const next=attempts+1;setAttempts(next);if(solved){onComplete({attempts:next,hintsUsed:used,durationMs:Date.now()-started.current});track('mission_completed',{missionId:id,attempts:next,hintsUsed:used});if(mission.number===5)track('chapter_completed',{chapter:mission.chapter});if(id==='c6m5')track('season_completed');setDone(true)}else{setMessage('A combinação ainda não revela a pista. Releia as dicas e tente novamente.');track('mission_failed',{missionId:id})}}
 const hint=()=>{if(used>=3)return;const cost=[0,20,40][used];dispatch({type:'USE_HINT',missionId:id,cost});track('hint_used',{missionId:id,cost:state.ravos>=cost?cost:0})}
 if(done)return <main className="flex min-h-dvh items-center px-6"><MissionComplete chapter={mission.number===5} reward={replay?{...mission.reward,xp:0,ravos:0}:mission.reward} onContinue={onNext}/></main>
 return <main className="mission-shell min-h-dvh pb-10 text-white"><header className="px-5 pb-5 pt-6"><button onClick={onExit} className="text-[10px] font-bold text-white/70">← SAIR E SALVAR</button><p className="eyebrow mt-7">Capítulo {mission.chapter} · Missão {mission.number} de 5 · {mission.duration}</p><h1 className="display mt-2 text-3xl font-black">{mission.title}</h1><p className="mt-2 text-xs text-white/70">{mission.location}</p></header><PuzzleContainer eyebrow={`Objetivo · ${mission.type}`} title={mission.prompt}><div className="mb-5"><div className="mb-2 flex justify-between text-[9px] font-bold"><span>SEQUÊNCIA REVELADA</span><span>{picked.length}/{mission.answer.length}</span></div><div className="h-2 rounded-full bg-white/15"><div className="h-full rounded-full bg-leaf transition-all" style={{width:`${picked.length/mission.answer.length*100}%`}}/></div></div><div className="mb-5 grid grid-cols-2 gap-2">{mission.options.map((option,i)=><button key={`${option}-${i}`} onClick={()=>add(option)} className="min-h-16 rounded-2xl border border-white/20 bg-white/10 p-3 text-xs font-black hover:border-gold">{option}</button>)}</div><div className="flex min-h-16 flex-wrap gap-2 rounded-2xl border border-dashed border-gold/40 p-3">{picked.map((p,i)=><span key={`${p}-${i}`} className="rounded-full bg-gold px-3 py-2 text-[10px] font-black text-ink">{i+1}. {p}</span>)}</div>{message&&<p className="mt-3 rounded-xl bg-red-400/15 p-3 text-xs">{message}</p>}{used>0&&<div className="mt-4 space-y-2">{mission.hints.slice(0,used).map((h,i)=><p key={h} className="rounded-xl bg-white/10 p-3 text-xs"><Lightbulb className="mr-2 inline text-gold" size={15}/>Dica {i+1}: {h}</p>)}</div>}<div className="mt-5 flex gap-2"><button onClick={hint} disabled={used>=3} className="btn flex-1 border border-white/20"><Lightbulb size={15}/>{used===0?'DICA GRÁTIS':used<3?`DICA · ${[0,20,40][used]} RAVOS`:'SEM MAIS DICAS'}</button><button onClick={()=>{setPicked([]);setMessage('')}} className="btn border border-white/20" aria-label="Limpar"><RotateCcw size={16}/></button></div><button onClick={verify} disabled={picked.length!==mission.answer.length} className="btn btn-primary mt-4 w-full">{solved?<><Check size={16}/>CONFIRMAR DESCOBERTA</>:<><Sparkles size={16}/>TESTAR COMBINAÇÃO</>}</button><p className="mt-3 text-center text-[9px] text-white/60">Sem RAVOS? As dicas continuam disponíveis gratuitamente para não bloquear a jornada.</p></PuzzleContainer></main>
}
