'use client'
import { useState } from 'react'
import { Anchor, Check, MapPin, QrCode, ScanLine, ShipWheel, Waves } from 'lucide-react'
import { culturalQuestions, missions } from '@/data/belem-content'
import type { MissionId } from '@/lib/game-types'
import { GameDialog, MissionComplete, PuzzleContainer } from './game-ui'

export function MissionExperience({id,onComplete,onExit}:{id:MissionId;onComplete:()=>void;onExit:()=>void}) {
  const mission=missions.find(item=>item.id===id)!
  const [done,setDone]=useState(false)
  const finish=()=>{onComplete();setDone(true)}
  if(done)return <main className="flex min-h-dvh items-center px-6"><MissionComplete chapter={id==='secret'} onContinue={onExit}/></main>
  return <main className="min-h-dvh pb-10"><header className="px-5 pb-5 pt-6"><button onClick={onExit} className="text-[10px] font-bold text-white/50">← SAIR E SALVAR</button><p className="eyebrow mt-7">Missão {mission.number} de 5 · {mission.duration}</p><h1 className="display mt-2 text-3xl font-black">{mission.title}</h1><p className="mt-2 text-xs text-white/45">{mission.location}</p></header>{id==='letter'&&<Letter finish={finish}/>} {id==='market'&&<Market finish={finish}/>} {id==='code'&&<Code finish={finish}/>} {id==='guardian'&&<Guardian finish={finish}/>} {id==='secret'&&<Secret finish={finish}/>}</main>
}

function Letter({finish}:{finish:()=>void}){const [step,setStep]=useState(0);return <PuzzleContainer eyebrow="Chuva sobre a Campina" title="Uma carta sem remetente">{step===0?<><div className="letter-paper rotate-[-1deg] rounded-sm p-6 text-[#18241e]"><p className="font-serif text-base leading-7">“A cidade não esqueceu. Sete partes guardam o caminho — e a primeira está onde a chuva encontra o rio.”</p><p className="mt-4 text-right font-serif text-xs">— Uma amiga da memória</p></div><button onClick={()=>setStep(1)} className="btn btn-primary mt-6 w-full">ROMPER O SELO</button></>:<GameDialog speaker="Mensagem desconhecida" choices={['Eu vou encontrar o mapa.','Antes, quero saber em quem confiar.']} onChoose={()=>setStep(2)}>Você encontrou o símbolo de uma embarcação desenhado sob o selo. O primeiro fragmento estava escondido no papel.</GameDialog>}{step===2&&<button onClick={finish} className="btn btn-primary mt-5 w-full">GUARDAR FRAGMENTO · CONCLUIR</button>}</PuzzleContainer>}

function Market({finish}:{finish:()=>void}){const [clues,setClues]=useState<number[]>([]);const [pick,setPick]=useState<number|null>(null);const q=culturalQuestions[0];const found=(i:number)=>setClues(c=>c.includes(i)?c:[...c,i]);return <PuzzleContainer eyebrow="Investigação visual" title={clues.length<3?'Encontre três sinais':'O peso da memória'}>{clues.length<3?<><p className="mb-4 text-xs leading-6 text-white/55">Observe a cena do mercado. Toque no barco, na balança e no rio marcados pelo brilho.</p><div className="market-scene relative h-72 overflow-hidden rounded-2xl border border-white/10"><div className="absolute inset-x-0 bottom-0 h-24 bg-gradient-to-t from-[#0a5662] to-[#176a72]"/><div className="absolute bottom-16 left-5 h-14 w-32 -rotate-3 rounded-[50%] bg-[#9b5f35]"/><div className="absolute bottom-24 left-14 h-20 w-1 bg-white/60"/><div className="absolute inset-x-0 top-10 text-center display text-2xl font-black text-white/10">VER-O-PESO</div>{([[16,65,ShipWheel],[68,38,Anchor],[75,75,Waves]] as const).map(([left,top,Icon],i)=><button aria-label={`Pista ${i+1}`} key={i} onClick={()=>found(i)} style={{left:`${left}%`,top:`${top}%`}} className={`clue absolute flex h-11 w-11 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full ${clues.includes(i)?'bg-leaf text-ink':'bg-gold/20 text-gold ring-1 ring-gold'}`}><Icon size={20}/></button>)}</div><p className="mt-3 text-center text-[10px] text-leaf">PISTAS ENCONTRADAS · {clues.length}/3</p></>:<><p className="text-sm font-bold leading-6">{q.question}</p><div className="mt-5 space-y-2">{q.options.map((option,i)=><button key={option} onClick={()=>setPick(i)} className={`w-full rounded-xl border p-3 text-left text-xs ${pick===i?(i===q.correctAnswer?'border-leaf bg-leaf/10':'border-red-400 bg-red-400/10'):'border-white/10'}`}>{option}</button>)}</div>{pick!==null&&<div className={`mt-4 rounded-xl p-3 text-[11px] leading-5 ${pick===0?'bg-leaf/10 text-leaf':'bg-red-400/10 text-red-200'}`}>{pick===0?q.explanation:'A marca não reage. Releia a pista e tente outra opção.'}</div>}{pick===q.correctAnswer&&<button onClick={finish} className="btn btn-primary mt-5 w-full">REGISTRAR DESCOBERTA</button>}</>}</PuzzleContainer>}

function Code({finish}:{finish:()=>void}){const symbols=['◈','≋','✦','⬡'];const target=['≋','◈','⬡','✦'];const [order,setOrder]=useState(symbols);const [selected,setSelected]=useState<number|null>(null);const solved=order.join('')===target.join('');function tap(i:number){if(selected===null){setSelected(i);return}const next=[...order];[next[selected],next[i]]=[next[i],next[selected]];setOrder(next);setSelected(null)}return <PuzzleContainer eyebrow="Puzzle de azulejos" title="Reordene o código"><p className="text-xs leading-6 text-white/55">O fragmento mostra a ordem: <b className="text-gold">RIO → ESTRELA → CASA → LUZ</b>. Toque em dois azulejos para trocá-los.</p><div className="mt-6 grid grid-cols-4 gap-2">{order.map((symbol,i)=><button key={`${symbol}-${i}`} onClick={()=>tap(i)} className={`aspect-square rounded-xl border text-2xl ${selected===i?'border-gold bg-gold/15':'border-river/30 bg-river/10'}`}>{symbol}</button>)}</div><div className="mt-5 flex justify-center gap-3 text-xl text-white/25">{target.map(x=><span key={x}>{x}</span>)}</div>{solved&&<><p className="mt-5 text-center text-xs font-bold text-leaf"><Check className="mr-1 inline" size={16}/> O azulejo oculto se abriu.</p><button onClick={finish} className="btn btn-primary mt-4 w-full">RECOLHER FRAGMENTO</button></>}</PuzzleContainer>}

function Guardian({finish}:{finish:()=>void}){const [stage,setStage]=useState(0);const [hint,setHint]=useState(false);return <PuzzleContainer eyebrow="Missão presencial · modo demo" title={stage===0?'Rota para o Forte':stage===1?'Checkpoint alcançado':'Sinal validado'}>{stage===0&&<><div className="topo relative h-64 overflow-hidden rounded-2xl bg-[#0a211a]"><div className="absolute -left-12 top-8 h-72 w-32 rotate-12 rounded-full bg-river/35"/><span className="absolute left-[55%] top-[30%] rounded-full bg-gold p-3 text-ink ring-4 ring-gold/20"><MapPin/></span><div className="absolute bottom-4 left-4 right-4 rounded-xl bg-ink/80 p-3 text-xs"><b>Forte do Presépio</b><p className="mt-1 text-[9px] text-white/40">Checkpoint de demonstração · 450 m</p></div></div><button onClick={()=>setStage(1)} className="btn btn-primary mt-5 w-full">SIMULAR CHEGADA AO CHECKPOINT</button></>}{stage===1&&<><div className="mx-auto flex h-48 w-48 items-center justify-center rounded-3xl bg-white text-ink"><QrCode size={130}/></div><button onClick={()=>setStage(2)} className="btn btn-primary mt-6 w-full"><ScanLine size={17}/> ESCANEAR CÓDIGO</button></>}{stage===2&&<><p className="text-sm leading-7 text-white/65">O Guardião pergunta: qual elemento conecta o Forte à origem da cidade?</p><button onClick={finish} className="mt-5 w-full rounded-xl border border-leaf bg-leaf/10 p-4 text-left text-xs font-bold">A posição estratégica junto à Baía do Guajará</button><button className="mt-2 w-full rounded-xl border border-white/10 p-4 text-left text-xs text-white/55" onClick={()=>setHint(true)}>Uma linha férrea subterrânea</button>{hint&&<p className="mt-3 text-[10px] text-red-200">O símbolo não reage. A cidade nasceu voltada para as águas.</p>}</>}</PuzzleContainer>}

function Secret({finish}:{finish:()=>void}){const [code,setCode]=useState<string[]>([]);const answer=['RIO','PESO','AZULEJO'];const solved=code.join()===answer.join();const add=(word:string)=>setCode(current=>current.length<3?[...current,word]:current);return <PuzzleContainer eyebrow="Boss puzzle" title="Abra o primeiro segredo"><p className="text-xs leading-6 text-white/55">Consulte suas memórias. Escolha, na ordem, o lugar onde a carta apontava, a origem do mercado e o código da Cidade Velha.</p><div className="my-5 grid grid-cols-3 gap-2">{[0,1,2].map(i=><div key={i} className="flex h-14 items-center justify-center rounded-xl border border-dashed border-gold/30 text-[10px] font-bold text-gold">{code[i]??'?'}</div>)}</div><div className="flex flex-wrap gap-2">{['RIO','FERROVIA','PESO','AZULEJO','MANGUEIRA'].map(word=><button key={word} disabled={code.includes(word)} onClick={()=>add(word)} className="rounded-full border border-white/10 px-3 py-2 text-[10px] font-bold disabled:opacity-25">{word}</button>)}</div>{code.length===3&&!solved&&<button onClick={()=>setCode([])} className="mt-5 w-full text-[10px] font-bold text-red-200">A CHAVE NÃO GIROU · TENTAR NOVAMENTE</button>}{solved&&<button onClick={finish} className="btn btn-primary mt-6 w-full">REVELAR O MAPA</button>}</PuzzleContainer>}
