'use client'
import { useState } from 'react'
import { Award, ChevronRight, Compass, Gift, Home, KeyRound, Map, MapPin, Medal, RotateCcw, Share2, Shield, Trophy, User, Waves } from 'lucide-react'
import { chapterTitle, missions } from '@/data/belem-content'
import { getMissionStatus } from '@/lib/game-engine'
import type { MissionId } from '@/lib/game-types'
import { GameProvider, useGame } from './game-provider'
import { ChapterProgress, CollectibleCard, CurrencyDisplay, MissionCard, RewardToast, Sheet, XPBar } from './game-ui'
import { MissionExperience } from './mission-experience'

type Screen='home'|'missions'|'map'|'collection'|'ranking'|'profile'|'rewards'
const marketImage='https://images.unsplash.com/photo-1596395819057-e37f55a8516b?auto=format&fit=crop&w=1200&q=85'

function Header({title}:{title?:string}){return <header className="flex items-center justify-between px-5 pb-4 pt-5"><div>{title?<><p className="eyebrow">RAVO · BELÉM</p><h1 className="display text-xl font-bold">{title}</h1></>:<div className="display text-2xl font-black tracking-[-.08em]">RA<span className="text-leaf">V</span>O</div>}</div><div className="flex h-10 w-10 items-center justify-center rounded-full border border-leaf/30 bg-leaf/10 text-xs font-black">RA</div></header>}
function Bottom({screen,set}:{screen:Screen;set:(s:Screen)=>void}){const nav:[Screen,typeof Home,string][]=[['home',Home,'Início'],['missions',Compass,'Missões'],['map',Map,'Mapa'],['collection',Award,'Coleção'],['profile',User,'Perfil']];return <nav className="fixed bottom-0 left-1/2 z-50 flex w-full max-w-[480px] -translate-x-1/2 justify-around border-t border-white/10 bg-[#071511ed] px-1 pb-[max(10px,env(safe-area-inset-bottom))] pt-2 backdrop-blur-xl">{nav.map(([s,Icon,label])=><button key={s} onClick={()=>set(s)} className={`flex min-w-12 flex-col items-center gap-1 rounded-xl px-2 py-1 text-[8px] font-bold ${screen===s?'bg-leaf/10 text-leaf':'text-white/40'}`}><Icon size={18}/>{label}</button>)}</nav>}

function HomeScreen({go,start}:{go:(s:Screen)=>void;start:(id:MissionId)=>void}){const {state,dispatch}=useGame();const current=missions.find(m=>getMissionStatus(state,m.id)==='in_progress')??missions.find(m=>getMissionStatus(state,m.id)==='available');return <><Header/><main className="px-5"><section className="hero relative overflow-hidden rounded-[28px] border border-white/10 p-6" style={{backgroundImage:`linear-gradient(90deg,#071511 5%,#071511c9 58%,transparent),url(${marketImage})`}}><div className="rain absolute inset-0"/><div className="relative z-10 max-w-[85%]"><p className="eyebrow text-gold">Temporada 01</p><h2 className="display mt-3 text-[38px] font-black leading-[.9]">BELÉM</h2><p className="display mt-2 text-lg font-bold">OS SEGREDOS DA CIDADE</p><p className="mt-3 text-[11px] leading-5 text-white/60">Um mapa antigo foi dividido. As ruas ainda guardam seus fragmentos.</p><button onClick={()=>{if(!state.started)dispatch({type:'START_CHAPTER'});current&&start(current.id)}} className="btn btn-primary mt-5">CONTINUAR JORNADA <ChevronRight size={15}/></button></div></section><section className="my-4 grid grid-cols-2 gap-3"><div className="glass rounded-2xl p-4"><XPBar xp={state.xp} compact/></div><div className="glass rounded-2xl p-4"><CurrencyDisplay value={state.ravos}/></div></section><ChapterProgress completed={state.completedMissions.length}/>{current&&<section className="mt-5"><div className="mb-3 flex items-end justify-between"><div><p className="eyebrow">Missão principal</p><h3 className="display text-lg font-bold">Próxima pista</h3></div><button onClick={()=>go('missions')} className="text-[9px] font-bold text-leaf">VER CAPÍTULO</button></div><MissionCard mission={current} status={getMissionStatus(state,current.id)} onClick={()=>start(current.id)}/></section>}<div className="mt-4 grid grid-cols-3 gap-2"><button onClick={()=>go('map')} className="glass rounded-2xl p-4 text-left"><Map className="text-river"/><b className="mt-3 block text-[10px]">MAPA</b></button><button onClick={()=>go('collection')} className="glass rounded-2xl p-4 text-left"><Award className="text-gold"/><b className="mt-3 block text-[10px]">COLEÇÃO</b></button><button onClick={()=>go('ranking')} className="glass rounded-2xl p-4 text-left"><Trophy className="text-leaf"/><b className="mt-3 block text-[10px]">RANKING</b></button></div></main></>}

function MissionsScreen({start}:{start:(id:MissionId)=>void}){const {state}=useGame();return <><Header title="Capítulo 1"/><main className="space-y-3 px-5"><div className="mb-5 rounded-2xl border border-gold/20 bg-gold/5 p-4"><p className="eyebrow text-gold">Arco atual</p><h2 className="display mt-1 text-xl font-bold">{chapterTitle}</h2><p className="mt-2 text-[10px] leading-5 text-white/45">Recupere os primeiros fragmentos e revele a história esquecida da cidade.</p></div>{missions.map(m=><MissionCard key={m.id} mission={m} status={getMissionStatus(state,m.id)} onClick={()=>start(m.id)}/>)}</main></>}

function MapScreen({start}:{start:(id:MissionId)=>void}){const {state}=useGame();const expeditionUnlocked=state.completedMissions.includes('secret');const regions=[['Ver-o-Peso','left-[19%] top-[58%]',state.completedMissions.length<3],['Cidade Velha','left-[62%] top-[67%]',state.completedMissions.length<2],['Campina','left-[50%] top-[33%]',false],['Nazaré','left-[73%] top-[22%]',!expeditionUnlocked],['Docas','left-[20%] top-[24%]',state.completedMissions.length<1],['São Brás','left-[75%] top-[48%]',true]] as const;return <><Header title="Mapa de Belém"/><main className="px-5"><div className="topo relative h-[520px] overflow-hidden rounded-[28px] border border-white/10 bg-[#0a211a]"><div className="absolute -left-16 top-10 h-[520px] w-48 rotate-6 rounded-[50%] bg-river/35"/><p className="absolute left-4 top-1/2 -rotate-90 display text-xs font-bold tracking-widest text-white/20">BAÍA DO GUAJARÁ</p>{regions.map(([name,pos,locked],i)=><button key={name} onClick={()=>!locked&&i<3&&start((['guardian','code','letter'] as MissionId[])[i])} disabled={locked} className={`absolute ${pos} -translate-x-1/2 rounded-full px-3 py-2 text-[8px] font-bold shadow-xl ${locked?'bg-white/10 text-white/30':'bg-leaf text-ink'}`}><MapPin className="mx-auto mb-1" size={14}/>{name}</button>)}{expeditionUnlocked&&<div className="expedition-pin absolute right-5 top-24 rounded-2xl border border-gold/40 bg-gold/10 p-3 text-right"><p className="eyebrow text-gold">Nova expedição</p><b className="display text-xs">ROTA DA BAÍA</b></div>}<div className="absolute bottom-4 left-4 right-4 glass rounded-2xl p-4"><p className="eyebrow">Legenda de exploração</p><p className="mt-2 text-[9px] leading-5 text-white/50">● Missão &nbsp; ◆ Presencial &nbsp; ◎ Checkpoint<br/>✦ Especial &nbsp; ★ Recompensa</p></div></div></main></>}

function Collection(){const {state}=useGame();const fragmentNames=['Carta da Campina','Mensagem decodificada','Mapa reconstruído','Pista do Mercado','Selo do Guardião','Expedição desconhecida','Memória desconhecida'];return <><Header title="Coleção"/><main className="px-5"><div className="glass mb-5 rounded-3xl p-5"><p className="eyebrow">Mapa antigo</p><h2 className="display mt-1 text-2xl font-black">Fragmentos {state.fragments.length}/7</h2><p className="mt-2 text-[10px] text-white/40">Cada parte preserva uma memória de Belém.</p></div><div className="grid grid-cols-2 gap-3">{fragmentNames.map((name,i)=><CollectibleCard key={name} title={`Fragmento ${i+1}`} detail={name} found={state.fragments.includes(i+1)} icon={<Waves/>}/>)}<CollectibleCard title="Chave do Guardião" detail={`${state.keys} encontrada`} found={state.keys>0} icon={<KeyRound/>}/><CollectibleCard title="Medalha" detail={state.medals[0]??''} found={state.medals.length>0} icon={<Medal/>}/><CollectibleCard title="Primeiro passo" detail="Concluiu sua primeira missão" found={state.completedMissions.length>0} icon={<Shield/>}/></div></main></>}

function Ranking(){const {state}=useGame();return <><Header title="Ranking"/><main className="px-5"><p className="mb-4 rounded-xl bg-leaf/10 p-3 text-[10px] text-leaf">Ranking demonstrativo · sem premiação financeira.</p>{[['Luna Guajará',3210],['Ana Jambu',2870],['Você',state.xp],['Ravi Tucupi',950]].sort((a,b)=>Number(b[1])-Number(a[1])).map(([name,xp],i)=><div key={String(name)} className={`mb-2 flex items-center gap-3 rounded-2xl border p-4 ${name==='Você'?'border-leaf/40 bg-leaf/10':'border-white/10 bg-white/[.03]'}`}><b className="text-white/40">{i+1}º</b><span className="flex h-9 w-9 items-center justify-center rounded-full bg-river/15 font-bold text-river">{String(name)[0]}</span><b className="flex-1 text-xs">{name}</b><span className="text-[10px] text-gold">{xp} XP</span></div>)}</main></>}

function Rewards(){return <><Header title="Recompensas"/><main className="px-5"><div className="rounded-3xl border border-leaf/20 bg-leaf/5 p-5"><Gift className="text-leaf"/><p className="eyebrow mt-4">Recompensa virtual</p><h2 className="display mt-1 text-xl font-bold">Itens para sua jornada</h2><p className="mt-2 text-[10px] leading-5 text-white/45">Em breve, RAVOS poderão desbloquear personalizações. Não podem ser comprados, sacados ou convertidos em dinheiro.</p></div><div className="mt-4 rounded-3xl border border-white/10 p-5 opacity-65"><p className="eyebrow text-gold">Recompensa real · Fase 2</p><h2 className="display mt-1 text-lg font-bold">Experiências parceiras</h2><p className="mt-2 text-[10px] leading-5 text-white/45">Catálogo apenas visual. Sem sorteios, pagamentos ou resgates nesta versão.</p><button disabled className="btn mt-4 w-full border border-white/10 text-white/40">INDISPONÍVEL NA DEMO</button></div></main></>}

function Profile({openRewards}:{openRewards:()=>void}){const {state,dispatch}=useGame();return <><Header title="Explorador"/><main className="px-5"><div className="text-center"><div className="mx-auto flex h-24 w-24 items-center justify-center rounded-full border-2 border-leaf bg-river/10 text-2xl font-black">RA</div><h2 className="display mt-3 text-xl font-bold">Rafa Amazônida</h2></div><div className="glass mt-5 rounded-3xl p-5"><XPBar xp={state.xp}/></div><button onClick={openRewards} className="glass mt-4 flex w-full items-center gap-3 rounded-2xl p-4 text-left"><Gift className="text-gold"/><b className="flex-1 text-xs">Recompensas e prêmio social</b><ChevronRight size={16}/></button><div className="mt-6"><p className="eyebrow mb-3">Histórico de XP</p>{state.xpHistory.length?state.xpHistory.map(entry=><div key={entry.id} className="flex border-b border-white/5 py-3 text-xs"><span className="flex-1">{entry.label}</span><b className="text-leaf">+{entry.amount} XP</b></div>):<p className="text-xs text-white/35">Sua jornada ainda vai começar.</p>}</div><button onClick={()=>dispatch({type:'RESET'})} className="mt-8 flex items-center gap-2 text-[9px] font-bold text-white/30"><RotateCcw size={13}/> REINICIAR DEMONSTRAÇÃO</button></main></>}

function App(){const {state,dispatch,hydrated}=useGame();const [screen,setScreen]=useState<Screen>('home');const [active,setActive]=useState<MissionId|null>(null);const [toast,setToast]=useState<{xp:number;ravos:number}|null>(null);const [social,setSocial]=useState(false);function start(id:MissionId){const s=getMissionStatus(state,id);if(s==='locked'||s==='completed')return;dispatch({type:'START_CHAPTER'});dispatch({type:'START_MISSION',missionId:id});setActive(id)}function complete(){if(!active)return;const reward=missions.find(m=>m.id===active)!.reward;dispatch({type:'COMPLETE_MISSION',missionId:active});setToast({xp:reward.xp,ravos:reward.ravos});setTimeout(()=>setToast(null),3000)}function nextMission(){if(!active)return;const currentIndex=missions.findIndex(m=>m.id===active);const next=missions[currentIndex+1];if(next){dispatch({type:'START_MISSION',missionId:next.id});setActive(next.id)}else{setActive(null);setScreen('map')}}if(!hydrated)return <div className="flex min-h-dvh items-center justify-center"><span className="eyebrow">Carregando jornada…</span></div>;if(active)return <><MissionExperience id={active} onComplete={complete} onNext={nextMission} onExit={()=>{setActive(null);setScreen('home')}}/><RewardToast show={!!toast} xp={toast?.xp??0} ravos={toast?.ravos??0}/></>;const views:Record<Screen,React.ReactNode>={home:<HomeScreen go={setScreen} start={start}/>,missions:<MissionsScreen start={start}/>,map:<MapScreen start={start}/>,collection:<Collection/>,ranking:<Ranking/>,profile:<Profile openRewards={()=>setSocial(true)}/>,rewards:<Rewards/>};return <div className="app-shell mx-auto min-h-dvh max-w-[480px] overflow-x-hidden pb-24 shadow-2xl"><div className="noise"/>{views[screen]}<Bottom screen={screen} set={setScreen}/>{social&&<Sheet title="Prêmio social" onClose={()=>setSocial(false)}><div className="space-y-3">{['Prêmio conquistado','Compartilhar conquista','Validação da parceria','Bônus virtual'].map((item,i)=><div key={item} className="flex items-center gap-3 rounded-xl border border-white/10 p-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-leaf/10 text-leaf">{i+1}</span><b className="text-xs">{item}</b></div>)}</div><button onClick={()=>setSocial(false)} className="btn btn-primary mt-5 w-full"><Share2 size={16}/> ENTENDI</button><p className="mt-3 text-[9px] leading-4 text-white/35">Interface de preparação: nenhuma rede social está integrada.</p></Sheet>}<RewardToast show={!!toast} xp={toast?.xp??0} ravos={toast?.ravos??0}/></div>}
export function RavoApp(){return <GameProvider><App/></GameProvider>}
